<script src="{{ asset('dist/assets/js/bootstrap.js') }}"></script>
<script src="{{ asset('dist/assets/js/app.js') }}"></script>
<script src="{{ asset('dist/assets/js/pages/horizontal-layout.js') }}"></script>
<script src="{{ asset('dist/assets/extensions/apexcharts/apexcharts.min.js') }}"></script>
<script src="{{ asset('dist/assets/js/pages/dashboard.js') }}"></script>
<script src="{{ asset('dist/assets/js/initTheme.js') }}"></script>
<script src="{{ asset('dist/assets/extensions/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('dist/assets/extensions/simple-datatables/umd/simple-datatables.js') }}"></script>
<script src="{{ asset('dist/assets/js/pages/simple-datatables.js') }}"></script>
<script src="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.js"></script>